apiVersion: v1
kind: ServiceAccount
metadata:
  name: devsecops-app
  namespace: devsecops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: devsecops-app-role
  namespace: devsecops
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: devsecops-app-rolebinding
  namespace: devsecops
subjects:
  - kind: ServiceAccount
    name: devsecops-app
    namespace: devsecops
roleRef:
  kind: Role
  name: devsecops-app-role
  apiGroup: rbac.authorization.k8s.io
