name: Semgrep SAST

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  semgrep:
    name: Semgrep Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262

      - name: Install Semgrep
        run: python3 -m pip install semgrep

      - name: Run Semgrep SAST
        run: semgrep scan --config auto --error .

      - name: Run Trivy SCA
        uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8
        with:
          scan-type: fs
          scanners: vuln
          severity: HIGH,CRITICAL
          exit-code: '1'
